version: '3.9'

services:

  pg_notifications:
    image: postgres:14.3
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_notifications:/var/lib/postgresql/data
      - ./databases/pg:/docker-entrypoint-initdb.d

volumes:
  pg_notifications:
